// CodeGear C++Builder
// Copyright (c) 1995, 2018 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'FormStand.pas' rev: 33.00 (Windows)

#ifndef FormstandHPP
#define FormstandHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <System.Classes.hpp>
#include <System.SysUtils.hpp>
#include <System.Generics.Collections.hpp>
#include <System.Threading.hpp>
#include <System.Rtti.hpp>
#include <FMX.Types.hpp>
#include <FMX.Controls.hpp>
#include <FMX.Forms.hpp>
#include <FMX.Layouts.hpp>
#include <SubjectStand.hpp>
#include <System.Generics.Defaults.hpp>
#include <System.Types.hpp>

//-- user supplied -----------------------------------------------------------

namespace Formstand
{
//-- forward type declarations -----------------------------------------------
class DELPHICLASS FormStandAttribute;
class DELPHICLASS FormInfoAttribute;
class DELPHICLASS AlignAttribute;
class DELPHICLASS ClipChildrenAttribute;
template<typename T> class DELPHICLASS TFormInfo__1;
class DELPHICLASS TFormStand;
//-- type declarations -------------------------------------------------------
typedef System::TMetaClass* TFormClass;

#pragma pack(push,4)
class PASCALIMPLEMENTATION FormStandAttribute : public Subjectstand::ContextAttribute
{
	typedef Subjectstand::ContextAttribute inherited;
	
public:
	/* TObject.Create */ inline __fastcall FormStandAttribute() : Subjectstand::ContextAttribute() { }
	/* TObject.Destroy */ inline __fastcall virtual ~FormStandAttribute() { }
	
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION FormInfoAttribute : public Subjectstand::ContextAttribute
{
	typedef Subjectstand::ContextAttribute inherited;
	
public:
	/* TObject.Create */ inline __fastcall FormInfoAttribute() : Subjectstand::ContextAttribute() { }
	/* TObject.Destroy */ inline __fastcall virtual ~FormInfoAttribute() { }
	
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION AlignAttribute : public Subjectstand::ContextAttribute
{
	typedef Subjectstand::ContextAttribute inherited;
	
private:
	Fmx::Types::TAlignLayout FAlign;
	
public:
	__fastcall AlignAttribute(const Fmx::Types::TAlignLayout AAlign);
	__property Fmx::Types::TAlignLayout Align = {read=FAlign, nodefault};
public:
	/* TObject.Destroy */ inline __fastcall virtual ~AlignAttribute() { }
	
};

#pragma pack(pop)

#pragma pack(push,4)
class PASCALIMPLEMENTATION ClipChildrenAttribute : public Subjectstand::ContextAttribute
{
	typedef Subjectstand::ContextAttribute inherited;
	
private:
	bool FClipChildren;
	
public:
	__fastcall ClipChildrenAttribute(const bool AClipChildren);
	__property bool ClipChildren = {read=FClipChildren, nodefault};
public:
	/* TObject.Destroy */ inline __fastcall virtual ~ClipChildrenAttribute() { }
	
};

#pragma pack(pop)

#pragma pack(push,4)
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION TFormInfo__1 : public Subjectstand::TSubjectInfo
{
	typedef Subjectstand::TSubjectInfo inherited;
	
private:
	T FForm;
	bool FFormIsOwned;
	Fmx::Layouts::TLayout* FFormContainer;
	TFormStand* __fastcall GetFormStand();
	
protected:
	virtual Fmx::Types::TFmxObject* __fastcall GetSubject();
	virtual void __fastcall SetSubject(Fmx::Types::TFmxObject* const Value);
	virtual bool __fastcall GetSubjectIsOwned();
	virtual void __fastcall SetSubjectIsOwned(const bool Value);
	virtual void __fastcall ParentAll(Fmx::Forms::TForm* const AForm, Fmx::Types::TFmxObject* const AContainer);
	virtual void __fastcall UnparentAll(Fmx::Forms::TForm* const AForm);
	virtual void __fastcall SetupSubjectContainer();
	virtual void __fastcall TeardownSubjectContainer();
	virtual void __fastcall InjectContextAttribute(Subjectstand::ContextAttribute* const AAttribute, System::Rtti::TRttiField* const AField, const System::TClass AFieldClassType);
	void __fastcall FreeFormContainer();
	
public:
	__fastcall virtual TFormInfo__1(TFormStand* const AFormStand, const T AForm, Fmx::Types::TFmxObject* const AParent, const System::UnicodeString AStandStyleName);
	System::Threading::_di_ITask __fastcall Show _DEPRECATED_ATTRIBUTE0 (const System::DelphiInterface<System::Sysutils::TProc__1<TFormInfo__1<T>*> > ABackgroundTask = (System::DelphiInterface<System::Sysutils::TProc__1<TFormInfo__1<T>*> >)(0x0), const System::DelphiInterface<System::Sysutils::TProc__1<TFormInfo__1<T>*> > AOnTaskComplete = (System::DelphiInterface<System::Sysutils::TProc__1<TFormInfo__1<T>*> >)(0x0), const bool AOnTaskCompleteSynchronized = true)/* overload */;
	void __fastcall Show()/* overload */;
	__property bool FormIsOwned = {read=FFormIsOwned, write=FFormIsOwned, nodefault};
	__property T Form = {read=FForm};
	__property TFormStand* FormStand = {read=GetFormStand};
	__property Fmx::Layouts::TLayout* FormContainer = {read=FFormContainer};
public:
	/* TSubjectInfo.Destroy */ inline __fastcall virtual ~TFormInfo__1() { }
	
};

#pragma pack(pop)

typedef void __fastcall (__closure *TOnGetFormClassEvent)(TFormStand* const ASender, Fmx::Types::TFmxObject* &AParent, System::UnicodeString &AStandStyleName, TFormClass &AFormClass);

class PASCALIMPLEMENTATION TFormStand : public Subjectstand::TSubjectStand
{
	typedef Subjectstand::TSubjectStand inherited;
	
private:
	TOnGetFormClassEvent FOnGetFormClass;
	System::Generics::Collections::TList__1<Fmx::Forms::TForm*>* FVisibleForms;
	
protected:
	System::Generics::Collections::TObjectDictionary__2<Fmx::Forms::TForm*,TFormInfo__1<Fmx::Forms::TForm*>*>* FFormInfos;
	virtual int __fastcall GetCount();
	template<typename T> TFormClass __fastcall GetFormClass(Fmx::Types::TFmxObject* &AParent, System::UnicodeString &AStandStyleName);
	virtual void __fastcall DoAfterHide(Subjectstand::TSubjectStand* const ASender, Subjectstand::TSubjectInfo* const ASubjectInfo);
	virtual void __fastcall DoBeforeShow(Subjectstand::TSubjectStand* const ASender, Subjectstand::TSubjectInfo* const ASubjectInfo);
	virtual void __fastcall DoClose(Fmx::Types::TFmxObject* const ASubject);
	
public:
	__fastcall virtual TFormStand(System::Classes::TComponent* AOwner);
	__fastcall virtual ~TFormStand();
	Fmx::Forms::TForm* __fastcall LastShownForm();
	virtual void __fastcall Remove(Fmx::Types::TFmxObject* ASubject);
	template<typename T> HIDESBASE void __fastcall CloseAll()/* overload */;
	virtual void __fastcall CloseAll(const System::DynamicArray<System::TClass> ARestrictTo)/* overload */;
	virtual void __fastcall CloseAllExcept(const System::DynamicArray<System::TClass> AExceptions)/* overload */;
	template<typename T> HIDESBASE void __fastcall HideAndCloseAll()/* overload */;
	virtual void __fastcall HideAndCloseAll(const System::DynamicArray<System::TClass> ARestrictTo)/* overload */;
	virtual void __fastcall HideAndCloseAllExcept(const System::DynamicArray<System::TClass> AExceptions)/* overload */;
	TFormInfo__1<Fmx::Forms::TForm*>* __fastcall FormInfo(Fmx::Forms::TForm* const AForm)/* overload */;
	TFormInfo__1<Fmx::Forms::TForm*>* __fastcall FormInfo(const TFormClass AFormClass)/* overload */;
	template<typename T> TFormInfo__1<T>* __fastcall FormInfo()/* overload */;
	template<typename T> TFormInfo__1<T>* __fastcall GetFormInfo(const bool ANewIfNotFound = true, Fmx::Types::TFmxObject* const AParent = (Fmx::Types::TFmxObject*)(0x0), const System::UnicodeString AStandStyleName = System::UnicodeString());
	template<typename T> TFormInfo__1<T>* __fastcall Use(const T AForm, Fmx::Types::TFmxObject* const AParent = (Fmx::Types::TFmxObject*)(0x0), const System::UnicodeString AStandStyleName = System::UnicodeString());
	template<typename T> TFormInfo__1<T>* __fastcall New(Fmx::Types::TFmxObject* const AParent = (Fmx::Types::TFmxObject*)(0x0), const System::UnicodeString AStandStyleName = System::UnicodeString());
	__property System::Generics::Collections::TObjectDictionary__2<Fmx::Forms::TForm*,TFormInfo__1<Fmx::Forms::TForm*>*>* FormInfos = {read=FFormInfos};
	__property System::Generics::Collections::TList__1<Fmx::Forms::TForm*>* VisibleForms = {read=FVisibleForms};
	
__published:
	__property TOnGetFormClassEvent OnGetSubjectClass = {read=FOnGetFormClass, write=FOnGetFormClass};
	/* Hoisted overloads: */
	
public:
	inline void __fastcall  CloseAll(){ Subjectstand::TSubjectStand::CloseAll(); }
	inline void __fastcall  CloseAll(const System::TClass ARestrictTo){ Subjectstand::TSubjectStand::CloseAll(ARestrictTo); }
	inline void __fastcall  CloseAllExcept(const System::TClass AException){ Subjectstand::TSubjectStand::CloseAllExcept(AException); }
	inline void __fastcall  HideAndCloseAll(){ Subjectstand::TSubjectStand::HideAndCloseAll(); }
	inline void __fastcall  HideAndCloseAll(const System::TClass ARestrictTo){ Subjectstand::TSubjectStand::HideAndCloseAll(ARestrictTo); }
	inline void __fastcall  HideAndCloseAllExcept(const System::TClass AException){ Subjectstand::TSubjectStand::HideAndCloseAllExcept(AException); }
	
};


//-- var, const, procedure ---------------------------------------------------
}	/* namespace Formstand */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_FORMSTAND)
using namespace Formstand;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// FormstandHPP
